### ISSUE TITLE
Problem with Member symbol

### ISSUE THREAD

**Issue by 18516979324** [SergeiSemenkov/eMondrian#12]
Hello,
Dimension query is not supported with & symbol. For example: [Date].[Year].&[2023]

Please can you help!

**Comment by SergeiSemenkov** [comment]
Hi,
I just checked on FoodMart Example.
Query
`select [Time].[Year].&[1997] on 0 from [Sales]`
works.

Do you get some error?

**Comment by 18516979324** [comment]
> 你好， 我刚刚查看了 FoodMart 示例。 查询 `select [Time].[Year].&[1997] on 0 from [Sales]` 有效。
> 
> 你有什么错误吗？

**Comment by 18516979324** [comment]
MDX ：SELECT [Measures].[ChargeSUM] ON 0,[Time].[YM].[Y].&[2023] ON 1 FROM [Charge];
Error message in picture
![image](https://github.com/SergeiSemenkov/eMondrian/assets/29674416/3ce647c6-fc34-4810-abeb-591c6d1be4a4)

![image](https://github.com/SergeiSemenkov/eMondrian/assets/29674416/7e8a2500-223d-4875-ac23-06d1d9edb0b6)
