### ISSUE TITLE
MDX ：SELECT [Measures].[ChargeSUM] ON 0,[Time].[YM].[Y].&[2023] ON 1 FROM [Charge];

### ISSUE THREAD

**Issue by 18516979324** [SergeiSemenkov/eMondrian#13]
MDX ：SELECT [Measures].[ChargeSUM] ON 0,[Time].[YM].[Y].&[2023] ON 1 FROM [Charge];
Error message in picture
![image](https://github.com/SergeiSemenkov/eMondrian/assets/29674416/3ce647c6-fc34-4810-abeb-591c6d1be4a4)

![image](https://github.com/SergeiSemenkov/eMondrian/assets/29674416/7e8a2500-223d-4875-ac23-06d1d9edb0b6)

_Originally posted by @18516979324 in https://github.com/SergeiSemenkov/eMondrian/issues/12#issuecomment-1697089102_

**Comment by SergeiSemenkov** [comment]
Hi,

Try to set 
mondrian.olap.SsasCompatibleNaming=true
in 
tomcat/latest/webapps/emondrian/WEB-INF/classes/mondrian.properties

Or write query in this style:
SELECT [Measures].[ChargeSUM] ON 0, [Time.YM].[Y].&[2023] ON 1 FROM [Charge]

**Comment by 18516979324** [comment]
Thank you, it should be my problem, FoodMart did not have such a situation
![image](https://github.com/SergeiSemenkov/eMondrian/assets/29674416/92d116f7-3a94-48c0-806f-6ce9e9913c7e)

**Comment by 18516979324** [comment]
The reason is that the Level lacks the uniqueMembers attribute
![image](https://github.com/SergeiSemenkov/eMondrian/assets/29674416/6dd738f9-6634-4348-9db9-7032483a981e)

**Comment by SergeiSemenkov** [comment]
When you added uniqueMembers the query with "&" started to work?

**Comment by 18516979324** [comment]
Yes，uniqueMembers="true"
