### ISSUE TITLE
How can I write an mdx query that slices by both a date range and dimension member value

### ISSUE THREAD

**Issue by 18516979324** [SergeiSemenkov/eMondrian#14]
I need to write an mdx query that limits its results by the value of a dimension but also by a date range
`SELECT [Measures].[SUM] ON 0  FROM [Charge] WHERE {[Time].[YQMD].[Y].&[2018]:[Time].[YQMD].[Y].&[2022]}`

But it is an empty result set

**Comment by SergeiSemenkov** [comment]
Try this

```
with member [Time].[Period] as 'Aggregate([Time].[YQMD].[Y].&[2018]:[Time].[YQMD].[Y].&[2022])'
SELECT [Measures].[SUM] ON 0 FROM [Charge] WHERE [Time].[Period]

```

**Comment by 18516979324** [comment]
I suspect it's the mondrian version, I'm trying to downgrade Mondrian-9.3 to 3.14

**Comment by SergeiSemenkov** [comment]
I don't think so. But try. I suggested working version above.

**Comment by 18516979324** [comment]
I downgraded mondrian to 3.14 and the above issues were resolved.
When no other solution was found, demoting Mondrian 3.14 was my only option at the moment
