### ISSUE TITLE
Incompatibility with Power BI without specifying a MDX Query

### ISSUE THREAD

**Issue by pablolc** [SergeiSemenkov/eMondrian#2]
If you try connect from Power BI using the "Import" option without a MDX query, an XMLA request with a method EXECUTE with  this query in the statement   "Select [CUBE_NAME], [BASE_CUBE_NAME], [CUBE_CAPTION] from $system.mdschema_cubes where [CUBE_SOURCE] = 1" is executed by emondrian, and this kind of query is not supported by emondrian.

**Comment by SergeiSemenkov** [comment]
Implemented in Relese v9.2.7.0. Check it out.

**Comment by SergeiSemenkov** [comment]
Implemented in Relese v9.2.7.0. Check it out.

**Comment by pablolc** [comment]
Thanks so much, I will test the new war you uploaded, but I see there are no modifications to the "SergeiSemenkov/mondrian" repository, are these modifications only configuration or has the "mondrian" repository simply not been updated yet?

**Comment by SergeiSemenkov** [comment]
It's at eMondrian branch.

**Comment by pablolc** [comment]
I was testing the release v9.2.7.0, and if you access from Excel using the option From Database-> from SQL Analysis Service Database(Import) witouth MDX query and emondrian has several catalogs configured,, the same cubes appears in all catalogs, and if you try to access to one cube, MS Escel shows the following error:

Feedback Type:
Frown (Error)

Error Message:
Object reference not set to an instance of an object.

Stack Trace:
System.NullReferenceException
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.Mashup.Host.WorkspaceWeb.Views.Navigator.Cube.ParameterizedCubeQueryTreeNode.ExtractParameterDetails(PreviewReference previewReference)
   at Microsoft.Mashup.Host.WorkspaceWeb.Views.Navigator.Cube.ParameterizedCubeQueryTreeNode.<>c__DisplayClass23_0.<DiscoverParameterEntries>b__0(PreviewReference previewReference)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)

Stack Trace Message:
Object reference not set to an instance of an object.

**Comment by SergeiSemenkov** [comment]
Really, there was a bug with catalogs. I have patched it in  v9.2.7.0. Download this release again, please.

**Comment by pablolc** [comment]
Thanks so much!

**Comment by pablolc** [comment]
HI, this works and you can see several catalogs with the new release, but in the old versions of Excel and also in Tableau, that they use MSOLAP, you only can see an only one catalog, is this the expected behavior?

**Comment by SergeiSemenkov** [comment]
I have fixed the bug with Excel catalogs and parched it in v9.2.7.0. But I didn't check it with Tableau.

**Comment by pablolc** [comment]
Thanks so much!

**Comment by pablolc** [comment]
It works correctly, thanks so much!
