### ISSUE TITLE
An error with the session is shown several times in the log when you connect emondrian with Excel or similar clients

### ISSUE THREAD

**Issue by pablolc** [SergeiSemenkov/eMondrian#3]
If you access to emondrian from Excel ou similar clients as SSAS, in the log the following message is displayed:
ERROR 2021-08-04T08:29:21.763 mondrian.xmla.XmlaServlet [] - No login credentials for found for session [ccjvf4g7te]  
It appears in each access to emondrian from Excel.

**Comment by SergeiSemenkov** [comment]
It's fixed and patched in release v9.2.7.0
