### ISSUE TITLE
Issue with the XMLA sessionID 

### ISSUE THREAD

**Issue by pablolc** [SergeiSemenkov/eMondrian#4]
If you connect Excel or Tableau with emondrian as a Microsoft Analysis Services Data Source.
Tableau or excel saves the XMLA sessionID associated with the data source. They send the XMLA request with the same sessionID and if you has to reinitialize emondrian, emondrian loses this sessionID and an error is thrown:
<SOAP-ENV:Fault>
  <faultcode>SOAP-ENV:Server.00HSHU01</faultcode>
  <faultstring>Unknown error handle soap header Session with id &#34;eayduru10y&#34; does not exist</faultstring>
  <faultactor>Mondrian</faultactor>
  <detail>
    <Error ErrorCode="3238789130" Description="The Mondrian XML: Session with id &#34;eayduru10y&#34; does not exist"/>
  </detail>
</SOAP-ENV:Fault>
And in the clients, the code error A7AED4D2 is displayed.
Is there any way to avoid this? for instance assigning a new sessionID to the client?

**Comment by SergeiSemenkov** [comment]
SessionIds are unique identifiers of each client session with server. One connection can have multiple sessions.
eMondrian supports sessions, session members and sets. So you can create session calculated measures, members and sets and share them between pivot tables and charts in one session. 
And each session is isolated from others.
When you reinitialize emondrian you kill all existing sessions.
It's the same behavior as in Analysis Services. 
If you restart Analysis Services you'll get the same error and the same behavior.
A client (Excel) have to close old session and create new one.
And Excel user after receiving error have to just repeat the same operation again.
