### ISSUE TITLE
Measure groups

### ISSUE THREAD

**Issue by alexoff13** [SergeiSemenkov/eMondrian#7]
Hello!
I have 16 measures and 16 calculated measures. I need to collapse these measures into a hierarchy (same as in mssql sas).

How can i do this?

**Comment by SergeiSemenkov** [comment]
Hey, use displayFolder attribute of Measure and CalculatedMeasure.

![image](https://user-images.githubusercontent.com/40644652/206121743-67f9ac03-b4df-4978-95b3-a51c308bf346.png)
